// File: pwm_simple.v
// Generated by MyHDL 0.11
// Date: Fri Nov 27 13:49:22 2020


`timescale 1ns/10ps

module pwm_simple (
    clk_i,
    pwm_o,
    threshold
);


input clk_i;
output pwm_o;
wire pwm_o;
input [7:0] threshold;

reg [7:0] cnt;



always @(posedge clk_i) begin: PWM_SIMPLE_LOC_INSTS_CHUNK_INSTS_0
    cnt <= (cnt + 1);
end



assign pwm_o = (cnt < threshold);

endmodule
